packages:
  - apps/*
  - packages/*
  - tooling/*
  - "!apps/web3"

catalog:
  # Auth
  "@auth/core": 0.37.2
  "@auth/prisma-adapter": ~2.7.2
  "next-auth": 5.0.0-beta.25

  # Dev tooling
  eslint: ^9.23.0
  prettier: ^3.5.3
  tailwindcss: ^3.4.15
  typescript: ^5.9.2

  # Misc
  zod: ^3.24.2

  # Tanstack & tRPC
  "@tanstack/react-query": ^5.69.0
  "@trpc/client": ^11.0.0
  "@trpc/tanstack-react-query": ^11.0.0
  "@trpc/server": ^11.0.0

  # Common UI utilities
  "class-variance-authority": ^0.7.1
  "clsx": ^2.1.1
  "tailwind-merge": ^3.3.1
  "lucide-react": ^0.540.0
  "sonner": ^2.0.7
  "jotai": ^2.13.1
  "react-error-boundary": ^6.0.0
  "tw-animate-css": ^1.3.7

  # Common libraries
  "bs58": ^6.0.0
  "bn.js": ^5.2.2

  # Node types
  "@types/node": ^22.13.11
  "@types/bn.js": ^5.2.0

catalogs:
  react19:
    react: 19.1.1
    react-dom: 19.1.1
    "@types/react": ^19.1.10
    "@types/react-dom": ^19.1.7

  react18:
    react: 18.2.0
    react-dom: 18.2.0
    "@types/react": ^18.2.0
    "@types/react-dom": ^18.2.0
