[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
web3 = "hvD9qm7aUZmbosN7pyYHKNAgthyWU8x1ybxPJoNv3LU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "vitest"
